"""Bengali-OCR research study records (S0 contracts)."""

from .config import StudyConfig
from .schema import (
    SCHEMA_VERSION,
    MANIFEST_VERSION,
    GOLD_FREE_FORBIDDEN_KEYS,
    ContractError,
    Split,
    PageNumberConvention,
    RightsBasis,
    GoldStatus,
    FailureState,
    DecisionAction,
    Geometry,
    SourcePage,
    SamplePage,
    GoldLine,
    GoldPage,
    Prediction,
    Candidate,
    Decision,
    Evaluation,
    Manifest,
    canonical_json,
    record_hash,
    assert_no_gold_fields,
    software_baseline,
)

__all__ = [
    "SCHEMA_VERSION",
    "MANIFEST_VERSION",
    "GOLD_FREE_FORBIDDEN_KEYS",
    "ContractError",
    "Split",
    "PageNumberConvention",
    "RightsBasis",
    "GoldStatus",
    "FailureState",
    "DecisionAction",
    "Geometry",
    "SourcePage",
    "SamplePage",
    "GoldLine",
    "GoldPage",
    "Prediction",
    "Candidate",
    "Decision",
    "Evaluation",
    "Manifest",
    "StudyConfig",
    "canonical_json",
    "record_hash",
    "assert_no_gold_fields",
    "software_baseline",
]
