from .assets import (
    AssetCandidate,
    AssetError,
    fetch_remote_cover,
    rank_cover_candidates,
    register_local_bytes,
    register_local_file,
    register_remote_cover,
    select_cover,
)
from .database import CatalogueDB
from .foundation import (
    CatalogueFoundation,
    ImportRun,
    LocalDocument,
    SourceSnapshot,
    file_sha256,
    ingest_local_documents,
    iter_local_documents,
)
from .importers.open_library import (
    OpenLibraryResult,
    cover_url,
    search_open_library,
    stage_open_library_dump,
)
from .isbn import is_valid_isbn, normalize_isbn, normalize_isbn10
from .matching import find_best_match, fuzzy_match_score, match_book, normalize_bengali
from .materialization import (
    NormalizedSource,
    materialize_source_records,
    parse_source_record,
)
from .models import (
    Author,
    AuthorRole,
    Book,
    BookAuthor,
    Bookmark,
    Favorite,
    FileRecord,
    ProcessingRecord,
    ProcessingState,
    ReadingList,
    ReadingProgress,
    Review,
    Subject,
    User,
)
from .resolution import accept_match, generate_candidates, reject_match, review_match
from .schema import get_db_connection, initialize_database
from .postgres import (
    PostgresCatalogueDB,
    PostgresUnavailableError,
    initialize_postgres,
    postgres_status,
    resolve_postgres_dsn,
)
from .search import (
    get_book_stats,
    rebuild_fts_index,
    search_books,
    search_books_with_authors,
)

__all__ = [
    "AssetCandidate",
    "AssetError",
    "Author",
    "AuthorRole",
    "Book",
    "BookAuthor",
    "Bookmark",
    "CatalogueDB",
    "CatalogueFoundation",
    "PostgresCatalogueDB",
    "PostgresUnavailableError",
    "Favorite",
    "FileRecord",
    "ImportRun",
    "LocalDocument",
    "NormalizedSource",
    "OpenLibraryResult",
    "ProcessingRecord",
    "ProcessingState",
    "ReadingList",
    "ReadingProgress",
    "Review",
    "SourceSnapshot",
    "Subject",
    "User",
    "accept_match",
    "cover_url",
    "fetch_remote_cover",
    "file_sha256",
    "find_best_match",
    "fuzzy_match_score",
    "generate_candidates",
    "get_book_stats",
    "get_db_connection",
    "ingest_local_documents",
    "initialize_database",
    "initialize_postgres",
    "is_valid_isbn",
    "iter_local_documents",
    "match_book",
    "materialize_source_records",
    "normalize_bengali",
    "normalize_isbn",
    "normalize_isbn10",
    "parse_source_record",
    "rank_cover_candidates",
    "rebuild_fts_index",
    "register_local_bytes",
    "register_local_file",
    "register_remote_cover",
    "postgres_status",
    "reject_match",
    "review_match",
    "search_books",
    "search_books_with_authors",
    "search_open_library",
    "select_cover",
    "stage_open_library_dump",
    "resolve_postgres_dsn",
]
